name: Build and Test ChimixCheatEngine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup MinGW-w64
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake

      - name: Install nlohmann/json
        run: |
          if not exist desktop-app\cpp-src\third-party mkdir desktop-app\cpp-src\third-party
          cd desktop-app/cpp-src/third-party
          git clone --depth 1 https://github.com/nlohmann/json.git

      - name: Copy nlohmann/json.hpp
        run: |
          if not exist desktop-app\include\nlohmann mkdir desktop-app\include\nlohmann
          copy desktop-app\cpp-src\third-party\json\single_include\nlohmann\json.hpp desktop-app\include\nlohmann\json.hpp

      - name: Install dependencies
        run: |
          cd desktop-app
          npm install

      - name: Build C++ engine
        run: |
          cd desktop-app/cpp-src
          if not exist build mkdir build
          cd build
          cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build .

      - name: Build Electron app
        run: |
          cd desktop-app
          npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ChimixCheatEngine
          path: desktop-app/dist/
