
name: Build and Test ChimixCheatEngine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup MinGW-w64
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake

      - name: Ensure third-party directory exists
        shell: pwsh
        run: |
          if (!(Test-Path "desktop-app/cpp-src/third-party")) { New-Item -ItemType Directory -Path "desktop-app/cpp-src/third-party" }

      - name: Clone nlohmann/json
        run: |
          git clone --depth 1 https://github.com/nlohmann/json.git desktop-app/cpp-src/third-party/json

      - name: Install dependencies
        run: |
          cd desktop-app
          npm install


      - name: Build C++ engine
        shell: pwsh
        run: |
          cd desktop-app/cpp-src
          if (!(Test-Path "build")) { New-Item -ItemType Directory -Path "build" }
          cd build
          cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build .

      - name: Ensure Electron packaging directory exists
        shell: pwsh
        run: |
          if (!(Test-Path "desktop-app/build")) { New-Item -ItemType Directory -Path "desktop-app/build" }

      - name: Copy C++ binary for Electron packaging
        shell: pwsh
        run: |
          Copy-Item -Path "desktop-app/cpp-src/build/ChimixEngine.exe" -Destination "desktop-app/build/ChimixEngine.exe" -Force

      - name: Rename C++ binary for Electron packaging
        shell: pwsh
        run: |
          if (Test-Path "desktop-app/build/ChimixCheatEngine.exe") {
              Remove-Item "desktop-app/build/ChimixCheatEngine.exe" -Force
          }
          if (Test-Path "desktop-app/build/ChimixEngine.exe") {
              Rename-Item -Path "desktop-app/build/ChimixEngine.exe" -NewName "ChimixCheatEngine.exe" -Force
          } else {
              Write-Error "desktop-app/build/ChimixEngine.exe not found. Rename aborted."
          }

      - name: Build Electron app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd desktop-app
          npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ChimixCheatEngine
          path: desktop-app/dist/
